FROM ${DOCKER_PREFIX}env:${PORTAL_ENV_TAG}${BUILD_ALPINE} as builder
USER root
RUN npm install -g typescript@$(jq .devDependencies.typescript package.json | tr -d '"')
RUN npm run build
RUN chown -R node:node /usr/src/app

FROM ${DOCKER_PREFIX}env:${PORTAL_ENV_TAG}${BUILD_ALPINE}
COPY --from=builder /usr/src/app/dist /usr/src/app/dist

EXPOSE 3002
